Abort if no images are found in an archive file

diff --git a/make-psx-bios-package b/make-psx-bios-package
--- a/make-psx-bios-package
+++ b/make-psx-bios-package
@@ -268,20 +268,33 @@ process_file() {
 			echo "--model cannot be used with an archive file" >&2
 			exit 1
 		fi
-		find "$WORK_DIR/tmp" -type f -size ${BIOS_SIZE}c |
+		FOUND=
+		find "$WORK_DIR/tmp" -type f -size ${BIOS_SIZE}c | {
 			# Keep in mind that the pipe created a subshell
+			FOUND=
 			while read FILENAME; do
-				process_file "$WORK_DIR" "$FILENAME" "recursive"
+				process_file "$WORK_DIR" "$FILENAME" "recursive" \
+					&& FOUND=true
 			done
+			[ "$FOUND" = true ]
+		} && FOUND=true
+		if [ ! "$FOUND" ]; then
+			echo "Could not find any images in $FILENAME" >&2
+			exit 1
+		fi
 		rm -rf "$WORK_DIR/tmp"
 	else
 		local SANITIZED_MODEL
 
 		local MODEL="$(get_model "$FILENAME")"
-		if [ ! "$MODEL" -a ! "$RECURSIVE" ]; then
-			echo "Cannot determine model for $FILENAME" >&2
-			if [ "$OPT_FORCE" = true -a "$OPT_MODEL" ]; then
-				echo "Overriding as requested by --force" >&2
+		if [ ! "$MODEL" ]; then
+			if [ ! "$RECURSIVE" ]; then
+				echo "Cannot determine model for $FILENAME" >&2
+				if [ "$OPT_FORCE" = true -a "$OPT_MODEL" ]; then
+					echo "Overriding as requested by --force" >&2
+				else
+					return 1
+				fi
 			else
 				return 1
 			fi
